### ISSUE TITLE
Translate Survey to Spanish

### ISSUE THREAD

**Issue by amchagas** [FOSH-following-demand/map_fosh_demand#4]
Once issue #3 is advanced and more crystallized version of the survey is present, we want to translate it to Spanish, so more people can interact with it. 

In order to make data analysis easier, the survey structure should be kept the same, including the question orders.

**Comment by gusma** [comment]
Only looking to translate the 28 fields in basic_overview.ipynb, correct?

**Comment by amchagas** [comment]
Hi @gusma 
thanks for dropping by :smile: Actually the source for the questions are here: https://github.com/amchagas/map_fosh_demand/blob/master/survey/questions/translation_first_draft.md

Also it would be nice to get comments on the questions themselves! Share, if you feel confortable, what you think about them, and if you think they could be made more appropriate for your context.

**Comment by gusma** [comment]
Translated, please check the PR and see if it's useful for you, thanks!

**Comment by amchagas** [comment]
great, thanks!

**Comment by amchagas** [comment]
Hi!
Thanks for the pointers! I made changes accordingly :)

**Comment by thessaly** [comment]
### Comments for spanish version :rainbow: 

- Welcome msg is not showing complete when I switch to Spanish

**Demographics**    
- Section title, description and first four questions are in English

**Educación**    
- Por favor díganos el último nivel educativo adquirido: // I'd change adquirido for alcanzado
- Formación o concentración // change for "Especialidad" 

**Work**
- Section title is in English
- typo in Q1 acadéMica, eStudiante
- Cuál es su área principal de trabajo // same as in English won't let input 'other'

**Tecnologías abiertas (Open Source)**
- I think this is a better version of the section description:

> El movimiento de código abierto está basado en la idea que todos los diseños y código de software, hardware y equipamiento así como artículos y protocolos pueden y deberían ser libremente distribuidos para uso, estudio, distribución y mejoramiento. Este movimiento comenzó en los años setenta, y ha ganado mucho terreno con la llegada de Internet. Algunos ejemplos de software de código abierto incluyen el navegador Firefox y el sistema operativo GNU / Linux.. 

- Q2: 'I wouldn't know' needs translation 'No lo sé'

**Using new brands / DIY equipment**    
- Title & Q2, 4 (and subquestion) in English
- Last question missing
